### ISSUE TITLE
Upload fails when uploading large PBIX file

### ISSUE THREAD

**Issue by ThomasDay** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#10]
Good morning Wallace and all those who are helping with the embedded project,
First, thanks to everyone for your work.  It's important stuff and I look forward to using our embedded model.

I've authored a pretty nice model of public healthcare data in powerbi.  I'd like to embed it into our website.  I reached out to you in April when we were just beginning our work--and we were able to upload a small sample model.  We're now ready with a fully functional model.  It's pretty large at 243MB all in.  The upload, however, fails.  It's 243MB, skinnied up from 264MB since I understand the size limit for embedding is 250MB.  Here's the debug list that points to the failure: 
'ProvisionSample.vshost.exe' (CLR v4.0.30319: ProvisionSample.vshost.exe): Loaded 'C:\Users\trday\Desktop\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\bin\Debug\Microsoft.Rest.ClientRuntime.dll'. Cannot find or open the PDB file.

Here's the entire [debug listing in a .txt file
[EmbedLogFile2016-06-20.txt](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/files/323470/EmbedLogFile2016-06-20.txt)

Any help you can provide would be very much appreciated.
Tom

**Comment by ThomasDay** [comment]
The issue turned out to be the timeout settings in the ProvisionSample project.  We changed changed the 90 second timeout to 60 minutes.  Worked great.  This is surely a common problem.

It is within the "CreateClient" function within Program.cs within ProvisionSample.  We changed line 600 of Program.cs to the following: 
client.HttpClient.Timeout = new TimeSpan(0, 60, 0);

Not sure what to do with this, but thought I'd share and thanks!
Tom

**Comment by wbreza** [comment]
Sorry for the late reply - Glad you figured it out.  Feel free to send in a pull request with the change so our community can take advantage of your findings.

**Comment by ThomasDay** [comment]
I don't really know how to do that--but I agree it's the thing to do.  I'll
ask around and get the skinny on how that's done.  Tom

**Comment by pbillava** [comment]
Hello have increased the timeout still its not uploading..My file size is 25 MB. Returns error 
Operation returned an invalid status code 'InternalServerError'
