### ISSUE TITLE
Can't Build Project

### ISSUE THREAD

**Issue by sgdunker** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#16]
I have just installed VS2015 and downloaded the project.  When I tried to build I get the following error.

Severity    Code    Description Project File    Line    Suppression State
Error       This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.1\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.  EmbedSample \Documents\power-bi-embedded-integrate-report-into-web-app-master\power-bi-embedded-integrate-report-into-web-app-master\EmbedSample\EmbedSample.csproj 267

**Comment by wbreza** [comment]
If you downloaded the project vs. cloning check the file path of where you have it extracted on your machine.  We have seen cases where the Nuget restore fails if installed in a location with a very long file path.

**Comment by sgdunker** [comment]
Thanks that was the issue.  Simply moved it to a folder on the root and everything worked.
