### ISSUE TITLE
Publishing to IIS

### ISSUE THREAD

**Issue by sgdunker** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#17]
Ok this has been frustrating.  I can build the project and run it locally from VS, but when I try and publish the project to my IIS server I am getting an error saying there is no default document. Looking at the directory I don't see a default.aspx, so how do I configure the site to load the page I see when I run from VS?

**Comment by wbreza** [comment]
The `EmbedSample` app is an ASP.NET MVC project.  There isn't a `default.aspx`.  Instead there are routes registered in the [RouteConfig.cs](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/master/EmbedSample/App_Start/RouteConfig.cs#L16) file.

Running the app at the root should default to the `Index` action within the [DashboardController](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/master/EmbedSample/Controllers/DashboardController.cs#L30)

Ensure your IIS server has at least .NET 4.5 installed and that all of the dependent Nuget packages are being deployed along with the application.

**Comment by sgdunker** [comment]
Ok I didn't realize the server didn't have .Net 4.5 installed.  I have added that and now I am getting the page to render however now the layout is all messed up.  I assume it is a stylesheet issue or maybe the nugget packages.  What packages should be installed?  I leveraged a web package deployment model to install it.

**Comment by wbreza** [comment]
Does it render correctly if you run it locally?  You are likely just missing some of the JS/CSS resources.  Try running fiddler and see if there are any 404 requests.  If so ensure they are included in the deployment.

**Comment by sgdunker** [comment]
Figured it out, the CSS and Images are absolute references not relative references.  I moved the app to a root site and it works.  Thanks,
