### ISSUE TITLE
Api Namespace 

### ISSUE THREAD

**Issue by asadhkhan** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#2]
I am trying to use the sample PowerBI Embedded project to test.  I have followed the instructions on:

https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/#key-flow

I have done all the prep work and have downloaded the Repo from gitHub and opened in Visual Studio 2015, and tried Build (as the instructions states, with out any updates).  

When I build i get 18 Errors and 48 Warnings:  I am listing info from the Output Window

---

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
NuGet Package restore failed for project ProvisionSample: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
NuGet Package restore failed for project EmbedSample: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
NuGet Package restore failed for project EmbedSample: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
NuGet Package restore failed for project ProvisionSample: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
Error occurred while restoring NuGet packages: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>------ Build started: Project: ProvisionSample, Configuration: Debug Any CPU ------
2>------ Build started: Project: EmbedSample, Configuration: Debug Any CPU ------
2>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\EmbedSample\EmbedSample.csproj(265,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.1\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.22.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms, Version=2.22.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.PowerBI.Api, Version=1.0.12.16089, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(5,25,5,28): error CS0234: The type or namespace name 'Api' does not exist in the namespace 'Microsoft.PowerBI' (are you missing an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(6,25,6,28): error CS0234: The type or namespace name 'Api' does not exist in the namespace 'Microsoft.PowerBI' (are you missing an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(18,31,18,38): error CS0234: The type or namespace name 'Clients' does not exist in the namespace 'Microsoft.IdentityModel' (are you missing an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(362,27,362,36): error CS0246: The type or namespace name 'Workspace' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(378,39,378,48): error CS0246: The type or namespace name 'Workspace' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(396,27,396,33): error CS0246: The type or namespace name 'Import' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\akhan1\Documents\BlueMetal Working Directory\OneDrive for Business\powerbi_embedded\power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs(488,27,488,41): error CS0246: The type or namespace name 'IPowerBIClient' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by wbreza** [comment]
Please move your local repo to a location with a short file path.  Visual studio has a bug and doesn't support long file paths very well.

**Comment by asadhkhan** [comment]
Hi wbreza, thanks fr the response.  I went ahead and made the path to local repo short as possible:

c:/.powerbi/webapp_master  (solution sits in here)

I am still getting the same errors , i have attached the screenshot.

![api_namespace](https://cloud.githubusercontent.com/assets/10181016/14863425/9eba9fa8-0c83-11e6-9f09-454262c35a6a.jpg)

Any insight on this would be helpful.

Thanks

**Comment by shoatman** [comment]
Sent from Outlook Mobilehttps://aka.ms/blhgte

On Wed, Apr 27, 2016 at 11:24 AM -0700, "asadhkhan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi wbreza, thanks fr the response. I went ahead and made the path to local repo short as possible:

c:/.powerbi/webapp_master (solution sits in here)

I am still getting the same errors , i have attached the screenshot.

[api_namespace]https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f10181016%2f14863425%2f9eba9fa8-0c83-11e6-9f09-454262c35a6a.jpg&data=01%7c01%7cshoatman%40microsoft.com%7cb05673c3de564e98a92808d36ec91c9d%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=Z7yRdgyhyVz%2fuw3lMxE56%2fhMiYfNbzFVvwBamChst5w%3d

Any insight on this would be helpful.

Thanks

##

**Comment by wbreza** [comment]
Looks like you are having an issue restoring Nuget packages.
Do you have Nuget Package restore enabled?  Go to Tools > Options > Package Manager to turn it on.

If so, right click on the solution and choose "Restore Nuget Packages".

If you continue to get error please reply with any additional error details from your output window.

**Comment by asadhkhan** [comment]
Thank you wbreza, that did the trick.   

Asad
