### ISSUE TITLE
Option #7 gives an error

### ISSUE THREAD

**Issue by julianmbs** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#20]
Hi,

When I try to update data source credentials (option #7), I get an error "Index was out of range. Must be non-negative and less than the size of the collection". When I debug it, I see that line 544 (client.Datasets.GetGatewayDatasourcesAsync) returns NULL to datasources variable, even though all the parameters are set correctly (workspaceCollectionName, workspaceId, and datasetKey). What could be the problem?

Thanks,
Julia

**Comment by wbreza** [comment]
Is your dataset a DirectQuery dataset?  Updating credentials is only supported on a direct query datasets.

**Comment by julianmbs** [comment]
Some of my datasets are DirectQuery and some are not, I would like to update the ones that are. Looks like the code takes the ID of the last dataset?

_datasets.Value[datasets.Value.Count - 1].Id_

Is that the problem?

**Comment by julianmbs** [comment]
I changed the code to make sure it takes the ID of the dataset that is DirectQuery for sure, but I am still getting NULL:

_var datasources = await client.Datasets.GetGatewayDatasourcesAsync(workspaceCollectionName, workspaceId, datasets.Value[0].Id);_

Any other ideas?

**Comment by wbreza** [comment]
Yes - you are correct.  This sample only illustrates updating the last dataset.  Feel free to augment to fit your needs.

We also have a more feature rich cross platform CLI tool that has better support than this sample.  Check it out @ https://github.com/Microsoft/PowerBI-Cli.
