### ISSUE TITLE
Will the dev/wabreza/aad-auth branch work with AAD B2C?

### ISSUE THREAD

**Issue by KevinHansel** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#23]
I found the branch that has been updated to authenticate against AAD.  Will this code also work with the new AAD B2C service?  If not, would you mind posting posting a version that does?  The new B2C service is very powerful and I'm sure many devs would appreciate it.

Thanks much.

Kevin

**Comment by wbreza** [comment]
No, the last AAD update did not target the new B2C service.  This update is only authenticating with Azure to call into the Power BI resource provider to provision Power BI workspace collections within Azure.

The Power BI Embedded service doesn't actually use Azure AD or have any concept of user accounts.  We use JWT tokens generated by 3rd party applications which control authorizing who can access reports, etc.

What scenario are you targeting?

**Comment by KevinHansel** [comment]
My interest in AAD B2C was for controlling user-level access to the web app itself.  I downloaded the original sample Power BI embedded dashboard web app and saw that it had a mocked-up a user account function (Emily Hart).  I was wondering if the newer aad-auth branch had added the code necessary to integrate with AAD for user-level access to the dashboard (i.e. enable the Emily Hart function to actually work).  Now I can see that the new branch only changed the code to authenticate with Azure for provisioning.

As for my target scenario, I want to create Power BI embedded dashboards (much like the sample) for several of my clients, leveraging AAD B2C to control user-level access to each dashboard (similar to the Emily Hart function).  Do you have any suggestions how best to go about integrating AAD B2C with the sample web app?

Thanks – appreciate it…

**Comment by wbreza** [comment]
I found this on the AAD B2C azure docs.  This looks like a good starting point.
https://azure.microsoft.com/en-us/documentation/articles/active-directory-b2c-devquickstarts-web-dotnet/

Looks like the standard Open ID Connect flow.  

Hope this helps.
