### ISSUE TITLE
Solution does not build

### ISSUE THREAD

**Issue by geordieboy** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#28]
Error   CS1061  'AuthenticationContext' does not contain a definition for 'AcquireTokenByRefreshTokenAsync' and no extension method 'AcquireTokenByRefreshTokenAsync' accepting a first argument of type 'AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)   ProvisionSample \power-bi-embedded-integrate-report-into-web-app-master\ProvisionSample\Program.cs  683 Active

**Comment by jvall** [comment]
Hey, what did you do to fix this? Getting the same error even after running an Update-Package for nuget.

**Comment by geordieboy** [comment]
Hey , initially I downloaded the source as a zip file which produced the bug ... I then did a git clone instead and that seemed to not produce the bug and built immediately without the package update.
weird eh.
