### ISSUE TITLE
Upload .pbix file Fail

### ISSUE THREAD

**Issue by ThomasDay** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#3]
Not sure how to debug what's wrong with an upload.  Have seen other powerbi.com postings of upload failing and I'm not sure howif they resolved theirs and therefore how to resolve mine.

![image](https://cloud.githubusercontent.com/assets/17302877/14916110/862dca74-0de5-11e6-9b79-71fae0b7d8a5.png)

As you can see all the proper credentials were entered.  I gave a valid path name, and the .pbix is not that large at 45mb.  
Any ideas here?  Thanks, Tom Day.

**Comment by wbreza** [comment]
This sample tool doesn't display verbose error output.  If you run a fiddler or other HTTP trace you may be able to see additional error information in the HTTP response.  

If you don't see any useful information please provide the "RequestId" response header and I can help you dig into it further.

**Comment by ThomasDay** [comment]
Hello Abreza--Thanks for that.  Very reassuring as I took another stab.  I used a smaller model built with the latest PowerBi and it uploaded successfully.  Not sure if either of those two things made a difference, but I'm pleased it uploaded successfully.

Thanks again,
Tom
