### ISSUE TITLE
Not able to delete or update connection string of dataset using Azure analysis services server as data source

### ISSUE THREAD

**Issue by bhavinrathod** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#49]
I have issue in deleting dataset with live connection to data source. Is there any work around to solve this issue?

**Comment by Michal7** [comment]
If you do not have any other datasets within workspace?

**Comment by bhavinrathod** [comment]
i have other datasets in workspace and i am using azure analysis services server as data source..if anybodt can help with connection string using azure analysis services server as data source

Even not able to update the dataset getting bad request error message.

**Comment by Michal7** [comment]
* Power BI Embedded is not yet supported in preview, so make sure that you are using GA version.

Regarding the origin issue you mentioned I have had the same issue.
I solved it by this workaround.

1. Create a new workspace collection
2. Create a new workspace and upload pbix file with Direct query( so I have one dataset within workspace)
3. Use ProvisionSample tool (remove first all configuration for app config) to update the connection string.
3.1 Enter user name
3.2 Enter user password
3.3 Enter connection string in the format : Data Source=xxxx.database.windows.net;Initial Catalog=dbName;User ID=xxx;Password=xxx  

Let me know if it work on your side.
