### ISSUE TITLE
The Project File Cannot be Loaded

### ISSUE THREAD

**Issue by MWilson929** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#6]
Hi,

I'm trying to open the Power BI Embedded visual studio solution to build the sample web app. However the project files fail to load. I'm getting the below error message;

\power-bi-embedded-integrate-report-into-web-app-master\EmbedSample\EmbedSample.csproj : error  : Value cannot be null.
Parameter name: url

Can anyone advise how to resolve this issue? 

Many Thanks,

Mark

**Comment by wbreza** [comment]
What version of Visual Studio are you using?  The sample should work with VS 2013 and above.

**Comment by MWilson929** [comment]
Hi,

I'm using VS2015;

Microsoft Visual Studio 2015 Shell (Integrated)
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.01038

Installed Version: IDE Standard

Microsoft Visual Studio Tools for Applications 2015   00322-10000-00000-AA576
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-10000-00000-AA576
Microsoft Visual Basic 2015

Visual C# 2015   00322-10000-00000-AA576
Microsoft Visual C# 2015

SQL Server Analysis Services   13.0.1601.5
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1601.5

SQL Server Data Tools   14.0.60525.0
Microsoft SQL Server Data Tools

SQL Server Integration Services  
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1601.5
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1601.5

**Comment by wbreza** [comment]
Are you cloning the git repo or downloading the source zip?  We haven't been able to reproduce this issue.  One issue we have seen is that the Nuget packages fail to restore when the repo is within a long file path.

**Comment by MWilson929** [comment]
Downloading the source zip. I've since installed visual studio community 2015 and been able to build the solution. 

I recently installed SQL Server 2016 so perhaps the issue was related to that version?! 

Thanks for your help
