### ISSUE TITLE
Provision Sample bug - Get Workspace Collection Metadata

### ISSUE THREAD

**Issue by RunReady** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#7]
Menu choice 2 shows an error when executed. Menu choices 5-7 work. Unable to tell if the problem is in the console app call, or in the remote API, as error/Exception messaging is not clear.
# What do you want to do?
1. Provision a new workspace collection
2. Get workspace collection metadata
3. Retrieve a workspace collection's API keys
4. Get list of workspaces within a collection
5. Provision a new workspace in an existing workspace collection
6. Import PBIX Desktop file into an existing workspace
7. Update connection string info for an existing dataset

**Comment by wbreza** [comment]
Options 1-3 currently require some special configuration to work.  You need to create a native application in your Azure AD that has delegated permissions to access your azure subscription / resource group.

You can following the instructions @ https://azure.microsoft.com/en-us/documentation/articles/resource-group-create-service-principal-portal/#get-access-token-in-code to set this up.  

After your Azure AD app is setup copy/paste the application client id and  paste it within the "clientId" setting in the app.config.

We we will be shipping native support in the Azure SDK soon which will allow you to use powershell commands or the cross platform command line tool to avoid this extra configuration.
