### ISSUE TITLE
Provision Sample bug - Get list of Workspaces within a Collection

### ISSUE THREAD

**Issue by RunReady** [Azure-Samples/power-bi-embedded-integrate-report-into-web-app#9]
Menu choice 4 shows an error when executed. Menu choices 5-7 work. Unable to tell if the problem is in the console app call, or in the remote API, as error/Exception messaging is not clear.
# What do you want to do?
1. Provision a new workspace collection
2. Get workspace collection metadata
3. Retrieve a workspace collection's API keys
4. Get list of workspaces within a collection
5. Provision a new workspace in an existing workspace collection
6. Import PBIX Desktop file into an existing workspace
7. Update connection string info for an existing dataset

**Comment by wbreza** [comment]
I'm not able to reproduce this.  Please ensure you are passing a valid workspace collection name and access key from your Azure subscription
